### ISSUE TITLE
Get Job Roles & Specialties

### ISSUE THREAD

**Issue by artgitex** [tomdev10/ibm-bluepages-js#17]
Iam still using your app and it helps me a lot.
There is a new section in BP - Job Roles & Specialties. Can you add the list of job roles to your app? 
![image](https://user-images.githubusercontent.com/45820574/143218517-f23baa4a-d5cd-4d99-973f-caadf52a28c2.png)

I see getJobFunctionByW3ID function, but it returns jobresponsibilities and not Job Roles.

Thank you in advance.

**Comment by rod4n4m1** [comment]
Hi, I moved to Kyndryl and I need someone from IBM to take it over. Thanks

**Comment by rod4n4m1** [comment]
Good news! @tomdev10 will take care of this package from now on.

**Comment by tomdev10** [comment]
Hi @artgitex apologies for the delay in tackling this issue, I have been taking time to find my way around this repo and underlying services. I've now fixed this, merged as release candidate `2.2.0`. I will publish this tomorrow, and close this issue once released. Many thanks for your support of this repo

**Comment by tomdev10** [comment]
This is now published, many thanks. Please use function `getJobRolesByW3ID` on version `2.2.0`

**Comment by artgitex** [comment]
Good news! Going to check this soon. Thanks!

**Comment by artgitex** [comment]
That is working fine, thank you very much!

**Comment by tomdev10** [comment]
You're welcome @artgitex - let me know if I can provide anything else for you 😊
